import {useEffect,useMemo,useState} from 'react';
import {CircleDollarSign,Database,Landmark,Plus,RefreshCw,Save,Truck,WalletCards} from 'lucide-react';
import {api,json} from '../../api';
import {rupiah} from '../../lib';
import type {Account,AccountType,CashBank,Masters,Supplier} from './types';
import {emptyMasters} from './types';

type Tab='accounts'|'suppliers'|'cashbank'|'opening';
const today=()=>new Date().toISOString().slice(0,10);
const labels:Record<AccountType,string>={ASSET:'Aset',LIABILITY:'Kewajiban',EQUITY:'Ekuitas',REVENUE:'Pendapatan',COGS:'HPP',EXPENSE:'Beban'};

export default function AccountingMaster({notify}:{notify:(s:string,error?:boolean)=>void}){
 const [data,setData]=useState<Masters>(emptyMasters),[tab,setTab]=useState<Tab>('accounts'),[loading,setLoading]=useState(true);
 const [accountEdit,setAccountEdit]=useState<Partial<Account>>({type:'EXPENSE',normal_balance:'DEBIT',report_group:'OPERATING_EXPENSE',cashflow_group:'OPERATING',sort_order:900,active:1});
 const [supplierEdit,setSupplierEdit]=useState<Partial<Supplier>>({active:1});
 const [cashEdit,setCashEdit]=useState<Partial<CashBank>>({kind:'BANK',active:1});
 const [openingDate,setOpeningDate]=useState(today()),[openingRows,setOpeningRows]=useState<{account_id:string;side:'DEBIT'|'CREDIT';amount:string}[]>([{account_id:'',side:'DEBIT',amount:''}]);
 async function load(){setLoading(true);try{setData(await api<Masters>('/admin/accounting/masters'));}catch(e){notify((e as Error).message,true);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const balanceAccounts=useMemo(()=>data.accounts.filter(a=>a.active&&!['REVENUE','COGS','EXPENSE'].includes(a.type)&&a.system_key!=='OPENING_EQUITY'),[data.accounts]);
 const assetAccounts=useMemo(()=>data.accounts.filter(a=>a.active&&a.type==='ASSET'),[data.accounts]);
 async function saveAccount(){try{const body={...accountEdit,active:accountEdit.active?1:0};if(accountEdit.id)await api(`/admin/accounting/accounts/${accountEdit.id}`,{method:'PUT',body:json(body)});else await api('/admin/accounting/accounts',{method:'POST',body:json(body)});notify('Master akun tersimpan.');setAccountEdit({type:'EXPENSE',normal_balance:'DEBIT',report_group:'OPERATING_EXPENSE',cashflow_group:'OPERATING',sort_order:900,active:1});await load();}catch(e){notify((e as Error).message,true);}}
 async function saveSupplier(){try{if(supplierEdit.id)await api(`/admin/accounting/suppliers/${supplierEdit.id}`,{method:'PUT',body:json(supplierEdit)});else await api('/admin/accounting/suppliers',{method:'POST',body:json(supplierEdit)});notify('Master supplier tersimpan.');setSupplierEdit({active:1});await load();}catch(e){notify((e as Error).message,true);}}
 async function saveCash(){try{if(cashEdit.id)await api(`/admin/accounting/cash-bank-master/${cashEdit.id}`,{method:'PUT',body:json(cashEdit)});else await api('/admin/accounting/cash-bank-master',{method:'POST',body:json(cashEdit)});notify('Master kas/bank tersimpan.');setCashEdit({kind:'BANK',active:1});await load();}catch(e){notify((e as Error).message,true);}}
 async function saveOpening(){try{const lines=openingRows.filter(x=>x.account_id&&Number(x.amount)>0).map(x=>({account_id:Number(x.account_id),side:x.side,amount:Number(x.amount)}));await api('/admin/accounting/opening-balance',{method:'POST',body:json({journal_date:openingDate,lines})});notify('Saldo awal berhasil diposting ke jurnal.');setOpeningRows([{account_id:'',side:'DEBIT',amount:''}]);}catch(e){notify((e as Error).message,true);}}
 const tabs:[Tab,string,typeof Database][]=[['accounts','Chart of Accounts',Database],['suppliers','Supplier',Truck],['cashbank','Kas & Bank',Landmark],['opening','Saldo Awal',CircleDollarSign]];
 return <section className="finance-page">
  <div className="admin-page-title"><div><span className="eyebrow">MASTER DATA AKUNTANSI</span><h2>Fondasi pencatatan keuangan</h2><p>COA, supplier, kas/bank, dan saldo awal menjadi sumber seluruh laporan keuangan.</p></div><button className="btn btn-outline" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
  <div className="finance-tabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={16}/>{label}</button>)}</div>
  {loading?<div className="finance-empty">Memuat master data...</div>:tab==='accounts'?<div className="finance-split">
   <div className="finance-card"><div className="finance-card-head"><div><b>{accountEdit.id?'Edit akun':'Tambah akun'}</b><span>Akun sistem dikunci pada kode/jenis agar posting otomatis tetap aman.</span></div></div><div className="finance-form-grid">
    <label>Kode<input value={accountEdit.code||''} disabled={!!accountEdit.system_key} onChange={e=>setAccountEdit({...accountEdit,code:e.target.value})}/></label>
    <label>Nama akun<input value={accountEdit.name||''} onChange={e=>setAccountEdit({...accountEdit,name:e.target.value})}/></label>
    <label>Jenis<select value={accountEdit.type||'EXPENSE'} disabled={!!accountEdit.system_key} onChange={e=>setAccountEdit({...accountEdit,type:e.target.value as AccountType})}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
    <label>Saldo normal<select value={accountEdit.normal_balance||'DEBIT'} disabled={!!accountEdit.system_key} onChange={e=>setAccountEdit({...accountEdit,normal_balance:e.target.value as 'DEBIT'|'CREDIT'})}><option value="DEBIT">Debit</option><option value="CREDIT">Kredit</option></select></label>
    <label>Kelompok laporan<input value={accountEdit.report_group||''} disabled={!!accountEdit.system_key} onChange={e=>setAccountEdit({...accountEdit,report_group:e.target.value.toUpperCase()})}/></label>
    <label>Arus kas<select value={accountEdit.cashflow_group||'OPERATING'} disabled={!!accountEdit.system_key} onChange={e=>setAccountEdit({...accountEdit,cashflow_group:e.target.value as Account['cashflow_group']})}><option value="OPERATING">Operasi</option><option value="INVESTING">Investasi</option><option value="FINANCING">Pendanaan</option><option value="NONE">Tidak dipakai</option></select></label>
    <label>Urutan<input type="number" value={accountEdit.sort_order??900} onChange={e=>setAccountEdit({...accountEdit,sort_order:Number(e.target.value)})}/></label>
    <label className="finance-check"><input type="checkbox" checked={accountEdit.active!==0} disabled={!!accountEdit.system_key} onChange={e=>setAccountEdit({...accountEdit,active:e.target.checked?1:0})}/> Aktif</label>
   </div><div className="finance-form-actions"><button className="btn btn-outline" onClick={()=>setAccountEdit({type:'EXPENSE',normal_balance:'DEBIT',report_group:'OPERATING_EXPENSE',cashflow_group:'OPERATING',sort_order:900,active:1})}>Baru</button><button className="btn btn-accent" onClick={saveAccount}><Save size={16}/> Simpan</button></div></div>
   <div className="finance-card finance-table-card"><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Kode</th><th>Akun</th><th>Jenis</th><th>Arus kas</th><th>Status</th></tr></thead><tbody>{data.accounts.map(a=><tr key={a.id} onClick={()=>setAccountEdit(a)} className="clickable"><td><b>{a.code}</b></td><td>{a.name}{a.system_key&&<small className="finance-system-tag">Sistem</small>}</td><td>{labels[a.type]}</td><td>{a.cashflow_group}</td><td>{a.active?'Aktif':'Nonaktif'}</td></tr>)}</tbody></table></div></div>
  </div>:tab==='suppliers'?<div className="finance-split">
   <div className="finance-card"><div className="finance-card-head"><div><b>{supplierEdit.id?'Edit supplier':'Tambah supplier'}</b><span>Supplier dipakai pada transaksi pembelian dan pembayaran hutang.</span></div></div><div className="finance-form-grid one-col"><label>Kode<input value={supplierEdit.code||''} onChange={e=>setSupplierEdit({...supplierEdit,code:e.target.value})}/></label><label>Nama<input value={supplierEdit.name||''} onChange={e=>setSupplierEdit({...supplierEdit,name:e.target.value})}/></label><label>WhatsApp / Telepon<input value={supplierEdit.phone||''} onChange={e=>setSupplierEdit({...supplierEdit,phone:e.target.value})}/></label><label>Email<input value={supplierEdit.email||''} onChange={e=>setSupplierEdit({...supplierEdit,email:e.target.value})}/></label><label>Alamat<textarea value={supplierEdit.address||''} onChange={e=>setSupplierEdit({...supplierEdit,address:e.target.value})}/></label><label className="finance-check"><input type="checkbox" checked={supplierEdit.active!==0} onChange={e=>setSupplierEdit({...supplierEdit,active:e.target.checked?1:0})}/> Aktif</label></div><div className="finance-form-actions"><button className="btn btn-outline" onClick={()=>setSupplierEdit({active:1})}>Baru</button><button className="btn btn-accent" onClick={saveSupplier}><Save size={16}/> Simpan</button></div></div>
   <div className="finance-card finance-table-card"><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Kode</th><th>Supplier</th><th>Kontak</th><th>Status</th></tr></thead><tbody>{data.suppliers.length?data.suppliers.map(s=><tr key={s.id} className="clickable" onClick={()=>setSupplierEdit(s)}><td><b>{s.code}</b></td><td>{s.name}</td><td>{s.phone||'-'}</td><td>{s.active?'Aktif':'Nonaktif'}</td></tr>):<tr><td colSpan={4}>Belum ada supplier. Tambahkan supplier pertama di panel kiri.</td></tr>}</tbody></table></div></div>
  </div>:tab==='cashbank'?<div className="finance-split">
   <div className="finance-card"><div className="finance-card-head"><div><b>{cashEdit.id?'Edit kas/bank':'Tambah kas/bank'}</b><span>Setiap kas/bank harus terhubung ke akun aset di COA.</span></div></div><div className="finance-form-grid one-col"><label>Kode<input value={cashEdit.code||''} disabled={!!cashEdit.id} onChange={e=>setCashEdit({...cashEdit,code:e.target.value})}/></label><label>Nama<input value={cashEdit.name||''} onChange={e=>setCashEdit({...cashEdit,name:e.target.value})}/></label>{!cashEdit.id&&<><label>Tipe<select value={cashEdit.kind||'BANK'} onChange={e=>setCashEdit({...cashEdit,kind:e.target.value as CashBank['kind']})}><option value="CASH">Kas</option><option value="BANK">Bank</option><option value="EWALLET">E-Wallet / QRIS</option></select></label><label>Akun COA<select value={cashEdit.account_id||''} onChange={e=>setCashEdit({...cashEdit,account_id:Number(e.target.value)})}><option value="">Pilih akun aset</option>{assetAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label></>}<label>Nama bank/provider<input value={cashEdit.bank_name||''} onChange={e=>setCashEdit({...cashEdit,bank_name:e.target.value})}/></label><label>No. rekening<input value={cashEdit.account_no||''} onChange={e=>setCashEdit({...cashEdit,account_no:e.target.value})}/></label><label>Atas nama<input value={cashEdit.account_holder||''} onChange={e=>setCashEdit({...cashEdit,account_holder:e.target.value})}/></label><label className="finance-check"><input type="checkbox" checked={cashEdit.active!==0} onChange={e=>setCashEdit({...cashEdit,active:e.target.checked?1:0})}/> Aktif</label></div><div className="finance-form-actions"><button className="btn btn-outline" onClick={()=>setCashEdit({kind:'BANK',active:1})}>Baru</button><button className="btn btn-accent" onClick={saveCash}><Save size={16}/> Simpan</button></div></div>
   <div className="finance-card finance-table-card"><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Kode</th><th>Kas / Bank</th><th>COA</th><th>Rekening</th><th>Status</th></tr></thead><tbody>{data.cash_bank.map(c=><tr key={c.id} className="clickable" onClick={()=>setCashEdit(c)}><td><b>{c.code}</b></td><td>{c.name}</td><td>{c.account_code} · {c.account_name}</td><td>{c.account_no||'-'}</td><td>{c.active?'Aktif':'Nonaktif'}</td></tr>)}</tbody></table></div></div>
  </div>:<div className="finance-card"><div className="finance-card-head"><div><b>Posting saldo awal</b><span>Masukkan saldo neraca saat mulai memakai modul akuntansi. Selisih otomatis masuk ke akun Saldo Awal / Laba Ditahan.</span></div><WalletCards size={22}/></div><div className="finance-opening-head"><label>Tanggal saldo awal<input type="date" value={openingDate} onChange={e=>setOpeningDate(e.target.value)}/></label><button className="btn btn-outline" onClick={()=>setOpeningRows([...openingRows,{account_id:'',side:'DEBIT',amount:''}])}><Plus size={15}/> Tambah baris</button></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Akun</th><th>Posisi</th><th>Nominal</th><th></th></tr></thead><tbody>{openingRows.map((r,i)=><tr key={i}><td><select value={r.account_id} onChange={e=>setOpeningRows(openingRows.map((x,n)=>n===i?{...x,account_id:e.target.value}:x))}><option value="">Pilih akun</option>{balanceAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></td><td><select value={r.side} onChange={e=>setOpeningRows(openingRows.map((x,n)=>n===i?{...x,side:e.target.value as 'DEBIT'|'CREDIT'}:x))}><option value="DEBIT">Debit</option><option value="CREDIT">Kredit</option></select></td><td><input type="number" min="0" value={r.amount} onChange={e=>setOpeningRows(openingRows.map((x,n)=>n===i?{...x,amount:e.target.value}:x))}/></td><td><button className="icon-btn" onClick={()=>setOpeningRows(openingRows.filter((_,n)=>n!==i))}>×</button></td></tr>)}</tbody></table></div><div className="finance-opening-total"><span>Total input</span><b>{rupiah(openingRows.reduce((n,x)=>n+(Number(x.amount)||0),0))}</b><button className="btn btn-accent" onClick={saveOpening}><Save size={16}/> Posting saldo awal</button></div></div>}
 </section>;
}
