import {useEffect,useMemo,useState} from 'react';
import {BarChart3,BookOpen,ClipboardList,FileSpreadsheet,RefreshCw,Scale,Waypoints} from 'lucide-react';
import {api} from '../../api';
import {rupiah} from '../../lib';
import type {Account,Masters} from './types';
import {emptyMasters} from './types';

type Tab='purchase-journal'|'general-ledger'|'profit-loss'|'balance-sheet'|'cash-flow'|'worksheet';
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,8)+'01';
const money=(v:unknown)=>rupiah(Number(v)||0);
const sideBalance=(raw:number)=>`${money(Math.abs(raw))} ${raw>=0?'D':'K'}`;

type PurchaseJournal={rows:Array<{purchase_date:string;purchase_no:string;supplier_invoice_no:string;supplier_code:string;supplier_name:string;payment_mode:string;cash_bank_name:string|null;total:number;journal_no:string}>;total:number};
type Ledger={account:Account;opening_raw:number;closing_raw:number;rows:Array<{journal_date:string;journal_no:string;source_type:string;reference_no:string|null;description:string;journal_description:string;debit:number;credit:number;running_raw:number}>};
type PL={rows:Array<{id:number;code:string;name:string;type:string;amount:number}>;totals:{revenue:number;cogs:number;gross_profit:number;expense:number;net_profit:number}};
type BS={assets:Array<{id:number;code:string;name:string;amount:number}>;liabilities:Array<{id:number;code:string;name:string;amount:number}>;equity:Array<{id:number;code:string;name:string;amount:number}>;current_earnings:number;totals:{assets:number;liabilities:number;equity:number}};
type CF={opening_cash:number;groups:{OPERATING:Array<{id:number;journal_date:string;journal_no:string;description:string;cash_delta:number}>;INVESTING:Array<{id:number;journal_date:string;journal_no:string;description:string;cash_delta:number}>;FINANCING:Array<{id:number;journal_date:string;journal_no:string;description:string;cash_delta:number}>};sums:{operating:number;investing:number;financing:number};net_change:number;ending_cash:number};
type WS={rows:Array<{id:number;code:string;name:string;type:string;opening_raw:number;period_debit:number;period_credit:number;ending_debit:number;ending_credit:number;pl_debit:number;pl_credit:number;bs_debit:number;bs_credit:number}>;net_profit:number};

export default function AccountingReports({notify}:{notify:(s:string,error?:boolean)=>void}){
 const [tab,setTab]=useState<Tab>('purchase-journal'),[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[masters,setMasters]=useState<Masters>(emptyMasters),[accountId,setAccountId]=useState(''),[loading,setLoading]=useState(false),[payload,setPayload]=useState<unknown>(null);
 const activeAccounts=useMemo(()=>masters.accounts.filter(a=>a.active),[masters.accounts]);
 useEffect(()=>{api<Masters>('/admin/accounting/masters').then(m=>{setMasters(m);if(!accountId&&m.accounts[0])setAccountId(String(m.accounts[0].id));}).catch(e=>notify((e as Error).message,true));},[]);
 async function load(which:Tab=tab){setLoading(true);try{let path='';if(which==='purchase-journal')path=`/admin/accounting/reports/purchase-journal?from=${from}&to=${to}`;if(which==='general-ledger'){if(!accountId){setPayload(null);return;}path=`/admin/accounting/reports/general-ledger?from=${from}&to=${to}&account_id=${accountId}`;}if(which==='profit-loss')path=`/admin/accounting/reports/profit-loss?from=${from}&to=${to}`;if(which==='balance-sheet')path=`/admin/accounting/reports/balance-sheet?as_of=${to}`;if(which==='cash-flow')path=`/admin/accounting/reports/cash-flow?from=${from}&to=${to}`;if(which==='worksheet')path=`/admin/accounting/reports/worksheet?from=${from}&to=${to}`;setPayload(await api(path));}catch(e){notify((e as Error).message,true);}finally{setLoading(false);}}
 useEffect(()=>{void load(tab);},[tab]);
 const tabs:[Tab,string,typeof ClipboardList][]=[['purchase-journal','Jurnal Pembelian',ClipboardList],['general-ledger','Buku Besar',BookOpen],['profit-loss','Laba Rugi',BarChart3],['balance-sheet','Neraca',Scale],['cash-flow','Arus Kas',Waypoints],['worksheet','Neraca Lajur',FileSpreadsheet]];
 return <section className="finance-page">
  <div className="admin-page-title"><div><span className="eyebrow">ACCOUNTING REPORTS</span><h2>Laporan Akuntansi</h2><p>Semua laporan membaca jurnal yang sama, jadi angka tetap nyambung dari transaksi sampai laporan.</p></div><button className="btn btn-outline" onClick={()=>load()}><RefreshCw size={16}/> Refresh</button></div>
  <div className="finance-tabs report-tabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setPayload(null);}}><Icon size={16}/>{label}</button>)}</div>
  <div className="finance-card report-filter"><label>Dari<input type="date" value={from} disabled={tab==='balance-sheet'} onChange={e=>setFrom(e.target.value)}/></label><label>{tab==='balance-sheet'?'Per tanggal':'Sampai'}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{tab==='general-ledger'&&<label>Akun<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Pilih akun</option>{activeAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>}<button className="btn btn-accent" onClick={()=>load()}>Tampilkan</button></div>
  {loading?<div className="finance-empty">Menghitung laporan...</div>:!payload?<div className="finance-empty">Pilih filter lalu tampilkan laporan.</div>:tab==='purchase-journal'?<PurchaseJournalView data={payload as PurchaseJournal}/>:tab==='general-ledger'?<LedgerView data={payload as Ledger}/>:tab==='profit-loss'?<ProfitLossView data={payload as PL}/>:tab==='balance-sheet'?<BalanceSheetView data={payload as BS}/>:tab==='cash-flow'?<CashFlowView data={payload as CF}/>:<WorksheetView data={payload as WS}/>} 
 </section>;
}

function PurchaseJournalView({data}:{data:PurchaseJournal}){return <div className="finance-card finance-table-card"><div className="finance-card-head"><div><b>Jurnal Pembelian</b><span>Dokumen pembelian yang sudah diposting.</span></div><strong>{money(data.total)}</strong></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Tanggal</th><th>No. Pembelian</th><th>Supplier</th><th>Invoice</th><th>Pembayaran</th><th>No. Jurnal</th><th>Total</th></tr></thead><tbody>{data.rows.length?data.rows.map((r,i)=><tr key={i}><td>{r.purchase_date}</td><td><b>{r.purchase_no}</b></td><td>{r.supplier_code} · {r.supplier_name}</td><td>{r.supplier_invoice_no||'-'}</td><td>{r.payment_mode==='CREDIT'?'Hutang':r.cash_bank_name||'Kas/Bank'}</td><td>{r.journal_no}</td><td className="money">{money(r.total)}</td></tr>):<tr><td colSpan={7}>Belum ada pembelian pada periode ini.</td></tr>}</tbody></table></div></div>}

function LedgerView({data}:{data:Ledger}){return <div className="finance-card finance-table-card"><div className="finance-card-head"><div><b>{data.account.code} · {data.account.name}</b><span>Saldo awal {sideBalance(data.opening_raw)} · Saldo akhir {sideBalance(data.closing_raw)}</span></div></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Tanggal</th><th>No. Jurnal</th><th>Referensi</th><th>Keterangan</th><th>Debit</th><th>Kredit</th><th>Saldo</th></tr></thead><tbody>{data.rows.length?data.rows.map((r,i)=><tr key={i}><td>{r.journal_date}</td><td><b>{r.journal_no}</b></td><td>{r.reference_no||'-'}</td><td>{r.description||r.journal_description}</td><td className="money">{r.debit?money(r.debit):'-'}</td><td className="money">{r.credit?money(r.credit):'-'}</td><td className="money">{sideBalance(r.running_raw)}</td></tr>):<tr><td colSpan={7}>Belum ada mutasi akun pada periode ini.</td></tr>}</tbody></table></div></div>}

function ProfitLossView({data}:{data:PL}){const revenue=data.rows.filter(x=>x.type==='REVENUE'),cogs=data.rows.filter(x=>x.type==='COGS'),expense=data.rows.filter(x=>x.type==='EXPENSE');return <div className="statement-grid"><Statement title="Pendapatan" rows={revenue}/><Statement title="Harga Pokok Penjualan" rows={cogs}/><div className="finance-statement-summary"><span>Laba Kotor</span><b>{money(data.totals.gross_profit)}</b></div><Statement title="Beban Operasional & Lainnya" rows={expense}/><div className={'finance-statement-summary grand '+(data.totals.net_profit<0?'negative':'')}><span>Laba / (Rugi) Bersih</span><b>{money(data.totals.net_profit)}</b></div></div>}
function Statement({title,rows}:{title:string;rows:Array<{id:number;code:string;name:string;amount:number}>}){return <div className="finance-card statement-card"><h3>{title}</h3>{rows.map(r=><div key={r.id}><span>{r.code} · {r.name}</span><b>{money(r.amount)}</b></div>)}</div>}

function BalanceSheetView({data}:{data:BS}){return <div className="balance-columns"><div><Statement title="Aset" rows={data.assets}/><div className="finance-statement-summary"><span>Total Aset</span><b>{money(data.totals.assets)}</b></div></div><div><Statement title="Kewajiban" rows={data.liabilities}/><Statement title="Ekuitas" rows={[...data.equity,{id:-1,code:'',name:'Laba berjalan',amount:data.current_earnings}]}/><div className="finance-statement-summary"><span>Total Kewajiban + Ekuitas</span><b>{money(data.totals.liabilities+data.totals.equity)}</b></div></div></div>}

function CashFlowView({data}:{data:CF}){const groups:[keyof CF['groups'],string][]=[['OPERATING','Aktivitas Operasi'],['INVESTING','Aktivitas Investasi'],['FINANCING','Aktivitas Pendanaan']];return <div className="statement-grid"><div className="finance-card cash-flow-summary"><span>Saldo kas awal</span><b>{money(data.opening_cash)}</b></div>{groups.map(([key,label])=><div className="finance-card statement-card" key={key}><h3>{label}</h3>{data.groups[key].length?data.groups[key].map(r=><div key={r.id}><span>{r.journal_date} · {r.description}</span><b className={r.cash_delta<0?'negative':''}>{money(r.cash_delta)}</b></div>):<div className="statement-empty">Tidak ada arus.</div>}<div className="statement-subtotal"><span>Netto {label.toLowerCase()}</span><b>{money(key==='OPERATING'?data.sums.operating:key==='INVESTING'?data.sums.investing:data.sums.financing)}</b></div></div>)}<div className="finance-statement-summary"><span>Kenaikan / (Penurunan) Kas</span><b>{money(data.net_change)}</b></div><div className="finance-statement-summary grand"><span>Saldo Kas Akhir</span><b>{money(data.ending_cash)}</b></div></div>}

function WorksheetView({data}:{data:WS}){return <div className="finance-card finance-table-card"><div className="finance-card-head"><div><b>Neraca Lajur</b><span>Saldo awal, mutasi periode, saldo akhir, kolom laba-rugi, dan neraca.</span></div><strong>Laba periode: {money(data.net_profit)}</strong></div><div className="finance-table-wrap worksheet-wrap"><table className="finance-table worksheet-table"><thead><tr><th rowSpan={2}>Kode</th><th rowSpan={2}>Akun</th><th colSpan={2}>Saldo Awal</th><th colSpan={2}>Mutasi</th><th colSpan={2}>Saldo Akhir</th><th colSpan={2}>Laba Rugi</th><th colSpan={2}>Neraca</th></tr><tr><th>D</th><th>K</th><th>D</th><th>K</th><th>D</th><th>K</th><th>D</th><th>K</th><th>D</th><th>K</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td><b>{r.code}</b></td><td>{r.name}</td><td className="money">{r.opening_raw>0?money(r.opening_raw):'-'}</td><td className="money">{r.opening_raw<0?money(-r.opening_raw):'-'}</td><td className="money">{r.period_debit?money(r.period_debit):'-'}</td><td className="money">{r.period_credit?money(r.period_credit):'-'}</td><td className="money">{r.ending_debit?money(r.ending_debit):'-'}</td><td className="money">{r.ending_credit?money(r.ending_credit):'-'}</td><td className="money">{r.pl_debit?money(r.pl_debit):'-'}</td><td className="money">{r.pl_credit?money(r.pl_credit):'-'}</td><td className="money">{r.bs_debit?money(r.bs_debit):'-'}</td><td className="money">{r.bs_credit?money(r.bs_credit):'-'}</td></tr>)}</tbody></table></div></div>}
