import {useEffect,useMemo,useState} from 'react';
import {ArrowDownLeft,ArrowLeftRight,ArrowUpRight,Landmark,RefreshCw,Save} from 'lucide-react';
import {api,json} from '../../api';
import {rupiah} from '../../lib';
import type {CashBank as CashBankType,Masters} from './types';
import {emptyMasters} from './types';

type Movement={id:number;transaction_no:string;transaction_date:string;direction:'IN'|'OUT'|'TRANSFER';cash_bank_name:string;target_cash_bank_name:string|null;counter_account_code:string|null;counter_account_name:string|null;supplier_name:string|null;amount:number;description:string;reference_no:string;journal_no:string|null};
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,8)+'01';

export default function CashBank({notify}:{notify:(s:string,error?:boolean)=>void}){
 const [masters,setMasters]=useState<Masters>(emptyMasters),[balances,setBalances]=useState<CashBankType[]>([]),[transactions,setTransactions]=useState<Movement[]>([]),[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[loading,setLoading]=useState(true);
 const [date,setDate]=useState(today()),[direction,setDirection]=useState<'IN'|'OUT'|'TRANSFER'>('OUT'),[source,setSource]=useState(''),[target,setTarget]=useState(''),[counter,setCounter]=useState(''),[supplier,setSupplier]=useState(''),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[reference,setReference]=useState('');
 const counterAccounts=useMemo(()=>masters.accounts.filter(a=>a.active&&!a.is_cash_bank),[masters.accounts]);const activeCash=masters.cash_bank.filter(c=>c.active);
 async function load(){setLoading(true);try{const [m,r]=await Promise.all([api<Masters>('/admin/accounting/masters'),api<{balances:CashBankType[];transactions:Movement[]}>(`/admin/accounting/cash-bank?from=${from}&to=${to}`)]);setMasters(m);setBalances(r.balances);setTransactions(r.transactions);if(!source&&m.cash_bank.find(x=>x.active))setSource(String(m.cash_bank.find(x=>x.active)!.id));}catch(e){notify((e as Error).message,true);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(){try{await api('/admin/accounting/cash-bank',{method:'POST',body:json({transaction_date:date,direction,cash_bank_account_id:Number(source),target_cash_bank_account_id:direction==='TRANSFER'?Number(target):null,counter_account_id:direction!=='TRANSFER'?Number(counter):null,supplier_id:supplier?Number(supplier):null,amount:Number(amount),description,reference_no:reference})});notify('Transaksi kas/bank dan jurnal berhasil diposting.');setAmount('');setDescription('');setReference('');setSupplier('');await load();}catch(e){notify((e as Error).message,true);}}
 return <section className="finance-page">
  <div className="admin-page-title"><div><span className="eyebrow">CASH & BANK CONTROL</span><h2>Cash & Bank</h2><p>Penerimaan, pengeluaran, transfer antar kas/bank, dan saldo berjalan dari jurnal.</p></div><button className="btn btn-outline" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
  <div className="cash-balance-grid">{balances.map(b=><article key={b.id} className="cash-balance-card"><Landmark size={19}/><div><span>{b.code}</span><b>{b.name}</b><small>{b.bank_name||b.kind}</small></div><strong>{rupiah(Number(b.balance||0))}</strong></article>)}</div>
  <div className="finance-card"><div className="finance-card-head"><div><b>Catat transaksi kas/bank</b><span>Setiap transaksi langsung membentuk jurnal double-entry.</span></div>{direction==='IN'?<ArrowDownLeft size={22}/>:direction==='OUT'?<ArrowUpRight size={22}/>:<ArrowLeftRight size={22}/>}</div><div className="finance-form-grid cash-entry"><label>Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Jenis<select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="IN">Uang masuk</option><option value="OUT">Uang keluar</option><option value="TRANSFER">Transfer antar kas/bank</option></select></label><label>Kas / Bank<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Pilih sumber</option>{activeCash.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label>{direction==='TRANSFER'?<label>Tujuan<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Pilih tujuan</option>{activeCash.filter(c=>String(c.id)!==source).map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label>:<label>Akun lawan<select value={counter} onChange={e=>setCounter(e.target.value)}><option value="">Pilih akun</option>{counterAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>}<label>Supplier (opsional)<select value={supplier} disabled={direction==='TRANSFER'} onChange={e=>setSupplier(e.target.value)}><option value="">Tanpa supplier</option>{masters.suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label>Nominal<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="span-2">Keterangan<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Contoh: Bayar listrik September"/></label><label>Referensi<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Opsional"/></label></div><div className="finance-form-actions"><button className="btn btn-accent" onClick={save}><Save size={16}/> Posting transaksi</button></div></div>
  <div className="finance-card finance-table-card"><div className="finance-card-head report-filter-head"><div><b>Mutasi kas & bank</b><span>Filter periode untuk melihat pergerakan transaksi.</span></div><div className="report-date-filter"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>s/d</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="btn btn-outline" onClick={load}>Terapkan</button></div></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Tanggal</th><th>No.</th><th>Kas/Bank</th><th>Jenis</th><th>Akun lawan / tujuan</th><th>Keterangan</th><th>Jurnal</th><th>Nominal</th></tr></thead><tbody>{loading?<tr><td colSpan={8}>Memuat...</td></tr>:transactions.length?transactions.map(t=><tr key={t.id}><td>{t.transaction_date}</td><td><b>{t.transaction_no}</b></td><td>{t.cash_bank_name}</td><td>{t.direction==='IN'?'Masuk':t.direction==='OUT'?'Keluar':'Transfer'}</td><td>{t.direction==='TRANSFER'?t.target_cash_bank_name:`${t.counter_account_code||''} ${t.counter_account_name||''}`}</td><td>{t.description}</td><td>{t.journal_no||'-'}</td><td className="money">{rupiah(Number(t.amount))}</td></tr>):<tr><td colSpan={8}>Belum ada transaksi pada periode ini.</td></tr>}</tbody></table></div></div>
 </section>;
}
