import {useEffect,useMemo,useState} from 'react';
import {Plus,RefreshCw,Save,ShoppingCart,Trash2} from 'lucide-react';
import {api,json} from '../../api';
import {rupiah} from '../../lib';
import type {Masters} from './types';
import {emptyMasters} from './types';
import {computePurchaseCosting,type PurchaseDiscountType} from './purchaseCosting';

type Line={kind:'PRODUCT'|'EXPENSE';product_id:string;account_id:string;description:string;quantity:string;unit_price:string;discount_type:PurchaseDiscountType;discount_value:string};
type Purchase={id:number;purchase_no:string;purchase_date:string;supplier_name:string;supplier_invoice_no:string;payment_mode:'CASH'|'CREDIT';cash_bank_name:string|null;gross_total?:number;item_discount_total?:number;invoice_discount_total?:number;landed_cost_total?:number;total:number;journal_no:string|null;items?:unknown[]};
const today=()=>new Date().toISOString().slice(0,10);
const newLine=():Line=>({kind:'PRODUCT',product_id:'',account_id:'',description:'',quantity:'1',unit_price:'',discount_type:'NONE',discount_value:''});
const n=(v:string)=>Number(v)||0;

export default function Purchases({notify}:{notify:(s:string,error?:boolean)=>void}){
 const [masters,setMasters]=useState<Masters>(emptyMasters),[rows,setRows]=useState<Purchase[]>([]),[loading,setLoading]=useState(true);
 const [purchaseDate,setPurchaseDate]=useState(today()),[supplierId,setSupplierId]=useState(''),[invoice,setInvoice]=useState(''),[payment,setPayment]=useState<'CASH'|'CREDIT'>('CASH'),[cashBankId,setCashBankId]=useState(''),[dueDate,setDueDate]=useState(''),[note,setNote]=useState(''),[lines,setLines]=useState<Line[]>([newLine()]);
 const [invoiceDiscountType,setInvoiceDiscountType]=useState<PurchaseDiscountType>('NONE'),[invoiceDiscountValue,setInvoiceDiscountValue]=useState(''),[landedCost,setLandedCost]=useState('');
 const expenseAccounts=useMemo(()=>masters.accounts.filter(a=>a.active&&!a.is_cash_bank&&['ASSET','COGS','EXPENSE'].includes(a.type)&&a.system_key!=='INVENTORY'),[masters.accounts]);
 const activeProducts=masters.products.filter(p=>p.active),activeSuppliers=masters.suppliers.filter(s=>s.active),activeCash=masters.cash_bank.filter(c=>c.active);
 const costing=useMemo(()=>computePurchaseCosting(lines.map(l=>({quantity:n(l.quantity),unitPrice:n(l.unit_price),discountType:l.discount_type,discountValue:n(l.discount_value),isProduct:l.kind==='PRODUCT'})),invoiceDiscountType,n(invoiceDiscountValue),n(landedCost)),[lines,invoiceDiscountType,invoiceDiscountValue,landedCost]);

 async function load(){setLoading(true);try{const [m,p]=await Promise.all([api<Masters>('/admin/accounting/masters'),api<{purchases:Purchase[]}>('/admin/accounting/purchases?from=2000-01-01&to=2099-12-31')]);setMasters(m);setRows(p.purchases);if(!supplierId&&m.suppliers.find(x=>x.active))setSupplierId(String(m.suppliers.find(x=>x.active)!.id));if(!cashBankId&&m.cash_bank.find(x=>x.active))setCashBankId(String(m.cash_bank.find(x=>x.active)!.id));}catch(e){notify((e as Error).message,true);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function update(i:number,patch:Partial<Line>){setLines(lines.map((x,index)=>index===i?{...x,...patch}:x));}
 function resetForm(){setInvoice('');setDueDate('');setNote('');setLines([newLine()]);setInvoiceDiscountType('NONE');setInvoiceDiscountValue('');setLandedCost('');}
 async function save(){
  try{
   if(!supplierId)throw new Error('Pilih supplier terlebih dahulu.');
   if(payment==='CASH'&&!cashBankId)throw new Error('Pilih kas / bank pembayaran.');
   if(lines.some(l=>!n(l.quantity)||!n(l.unit_price)))throw new Error('Qty dan harga beli setiap baris wajib diisi.');
   if(lines.some(l=>l.kind==='PRODUCT'&&!l.product_id)||lines.some(l=>l.kind==='EXPENSE'&&!l.account_id))throw new Error('Pilih produk atau akun untuk setiap baris.');
   if(lines.some(l=>l.discount_type==='PERCENT'&&n(l.discount_value)>100))throw new Error('Diskon item persen maksimal 100%.');
   if(lines.some(l=>l.discount_type==='AMOUNT'&&n(l.discount_value)>n(l.unit_price)))throw new Error('Diskon rupiah per unit tidak boleh melebihi harga beli.');
   if(invoiceDiscountType==='PERCENT'&&n(invoiceDiscountValue)>100)throw new Error('Diskon invoice persen maksimal 100%.');
   if(invoiceDiscountType==='AMOUNT'&&n(invoiceDiscountValue)>costing.subtotalAfterItemDiscount)throw new Error('Diskon invoice tidak boleh melebihi subtotal setelah diskon item.');
   if(n(landedCost)>0&&!lines.some(l=>l.kind==='PRODUCT'))throw new Error('Biaya pembelian / landed cost hanya dapat dialokasikan jika ada item produk/stok.');
   const items=lines.map(l=>({product_id:l.kind==='PRODUCT'?Number(l.product_id)||null:null,account_id:l.kind==='EXPENSE'?Number(l.account_id)||null:null,description:l.description,quantity:n(l.quantity),unit_price:n(l.unit_price),discount_type:l.discount_type,discount_value:n(l.discount_value)}));
   await api('/admin/accounting/purchases',{method:'POST',body:json({purchase_date:purchaseDate,supplier_id:Number(supplierId),supplier_invoice_no:invoice,payment_mode:payment,cash_bank_account_id:payment==='CASH'?Number(cashBankId):null,due_date:payment==='CREDIT'?dueDate||null:null,note,invoice_discount_type:invoiceDiscountType,invoice_discount_value:n(invoiceDiscountValue),landed_cost_total:n(landedCost),items})});
   notify('Pembelian diposting. Diskon, landed cost, stok, average cost, HPP, dan jurnal sudah diperbarui.');resetForm();await load();
  }catch(e){notify((e as Error).message,true);}
 }
 return <section className="finance-page">
  <div className="admin-page-title"><div><span className="eyebrow">PURCHASE TO ACCOUNTING</span><h2>Pembelian</h2><p>Harga beli dikurangi diskon, lalu diskon invoice dan biaya pembelian dialokasikan otomatis untuk membentuk HPP final.</p></div><button className="btn btn-outline" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
  <div className="finance-card purchase-entry"><div className="finance-card-head"><div><b>Transaksi pembelian baru</b><span>HPP produk menggunakan nilai bersih setelah seluruh diskon + alokasi biaya pembelian.</span></div><ShoppingCart size={22}/></div>
   <div className="finance-form-grid purchase-header"><label>Tanggal<input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)}/></label><label>Supplier<select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Pilih supplier</option>{activeSuppliers.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label>No. invoice supplier<input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="Opsional"/></label><label>Pembayaran<select value={payment} onChange={e=>setPayment(e.target.value as 'CASH'|'CREDIT')}><option value="CASH">Tunai / Bank</option><option value="CREDIT">Kredit / Hutang</option></select></label>{payment==='CASH'?<label>Kas / Bank<select value={cashBankId} onChange={e=>setCashBankId(e.target.value)}><option value="">Pilih kas/bank</option>{activeCash.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label>:<label>Jatuh tempo<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label>}<label className="span-2">Catatan<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Catatan pembelian"/></label></div>

   <div className="finance-table-wrap"><table className="finance-table purchase-lines purchase-costing-lines"><thead><tr><th>Tipe</th><th>Item / Akun</th><th>Keterangan</th><th>Qty</th><th>Harga beli / unit</th><th>Diskon item</th><th>Harga net / unit</th><th>HPP final / unit</th><th>Jumlah final</th><th></th></tr></thead><tbody>{lines.map((l,i)=>{const c=costing.rows[i];const netUnit=c&&c.quantity?Math.round((c.netBeforeInvoice/c.quantity)*100)/100:0;return <tr key={i}><td><select value={l.kind} onChange={e=>update(i,{kind:e.target.value as Line['kind'],product_id:'',account_id:''})}><option value="PRODUCT">Produk / Stok</option><option value="EXPENSE">Non-stok</option></select></td><td>{l.kind==='PRODUCT'?<select value={l.product_id} onChange={e=>{const p=activeProducts.find(x=>x.id===Number(e.target.value));update(i,{product_id:e.target.value,description:p?`${p.name}${p.variant?` · ${p.variant}`:''}`:''});}}><option value="">Pilih produk</option>{activeProducts.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}{p.variant?` · ${p.variant}`:''}</option>)}</select>:<select value={l.account_id} onChange={e=>update(i,{account_id:e.target.value})}><option value="">Pilih akun</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select>}</td><td><input value={l.description} onChange={e=>update(i,{description:e.target.value})}/></td><td><input type="number" min="0.001" step="0.001" value={l.quantity} onChange={e=>update(i,{quantity:e.target.value})}/></td><td><input type="number" min="0" step="1" value={l.unit_price} onChange={e=>update(i,{unit_price:e.target.value})} placeholder="0"/></td><td><div className="purchase-discount-cell"><select value={l.discount_type} onChange={e=>update(i,{discount_type:e.target.value as PurchaseDiscountType,discount_value:e.target.value==='NONE'?'':l.discount_value})}><option value="NONE">Tanpa diskon</option><option value="AMOUNT">Rp / unit</option><option value="PERCENT">%</option></select><input type="number" min="0" step={l.discount_type==='PERCENT'?'0.01':'1'} disabled={l.discount_type==='NONE'} value={l.discount_value} onChange={e=>update(i,{discount_value:e.target.value})} placeholder={l.discount_type==='PERCENT'?'0%':'Rp 0'}/></div></td><td className="money"><b>{rupiah(netUnit)}</b></td><td className="money final-cost"><b>{rupiah(c?.finalUnitCost||0)}</b>{c&&c.landedCostAlloc>0?<small>+ biaya {rupiah(c.landedCostAlloc)}</small>:null}</td><td className="money"><b>{rupiah(c?.finalAmount||0)}</b></td><td><button className="icon-btn" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,index)=>index!==i))}><Trash2 size={15}/></button></td></tr>;})}</tbody></table></div>

   <div className="purchase-costing-panel">
    <div className="purchase-costing-controls"><button className="btn btn-outline" onClick={()=>setLines([...lines,newLine()])}><Plus size={15}/> Tambah baris</button><label><span>Diskon invoice</span><div className="purchase-inline-input"><select value={invoiceDiscountType} onChange={e=>{const v=e.target.value as PurchaseDiscountType;setInvoiceDiscountType(v);if(v==='NONE')setInvoiceDiscountValue('');}}><option value="NONE">Tidak ada</option><option value="AMOUNT">Rp</option><option value="PERCENT">%</option></select><input type="number" min="0" step={invoiceDiscountType==='PERCENT'?'0.01':'1'} disabled={invoiceDiscountType==='NONE'} value={invoiceDiscountValue} onChange={e=>setInvoiceDiscountValue(e.target.value)} placeholder="0"/></div></label><label><span>Biaya pembelian / landed cost</span><input type="number" min="0" step="1" value={landedCost} onChange={e=>setLandedCost(e.target.value)} placeholder="Contoh: ongkir supplier"/><small>Dialokasikan proporsional hanya ke item produk/stok dan masuk HPP.</small></label></div>
    <div className="purchase-costing-summary"><div><span>Bruto</span><b>{rupiah(costing.grossTotal)}</b></div><div><span>Diskon item</span><b>- {rupiah(costing.itemDiscountTotal)}</b></div><div><span>Diskon invoice</span><b>- {rupiah(costing.invoiceDiscountTotal)}</b></div><div><span>Biaya pembelian</span><b>+ {rupiah(costing.landedCostTotal)}</b></div><div className="purchase-total"><span>Total dibayar / hutang</span><b>{rupiah(costing.total)}</b></div><button className="btn btn-accent" onClick={save}><Save size={16}/> Posting pembelian</button></div>
   </div>
  </div>
  <div className="finance-card finance-table-card"><div className="finance-card-head"><div><b>Riwayat pembelian</b><span>Total sudah merupakan nilai bersih setelah diskon + biaya pembelian.</span></div></div><div className="finance-table-wrap"><table className="finance-table purchase-history"><thead><tr><th>Tanggal</th><th>No. pembelian</th><th>Supplier</th><th>Bruto</th><th>Total diskon</th><th>Biaya pembelian</th><th>Total</th><th>Jurnal</th></tr></thead><tbody>{loading?<tr><td colSpan={8}>Memuat...</td></tr>:rows.length?rows.map(r=>{const gross=Number(r.gross_total??r.total);const discount=Number(r.item_discount_total||0)+Number(r.invoice_discount_total||0);return <tr key={r.id}><td>{r.purchase_date}</td><td><b>{r.purchase_no}</b><small className="table-subline">{r.supplier_invoice_no||'Tanpa invoice supplier'}</small></td><td>{r.supplier_name}<small className="table-subline">{r.payment_mode==='CASH'?(r.cash_bank_name||'Kas/Bank'):'Hutang'}</small></td><td className="money">{rupiah(gross)}</td><td className="money">{discount?`- ${rupiah(discount)}`:'-'}</td><td className="money">{Number(r.landed_cost_total||0)?`+ ${rupiah(Number(r.landed_cost_total))}`:'-'}</td><td className="money"><b>{rupiah(Number(r.total))}</b></td><td>{r.journal_no||'-'}</td></tr>}):<tr><td colSpan={8}>Belum ada transaksi pembelian.</td></tr>}</tbody></table></div></div>
 </section>;
}
