CREATE DATABASE IF NOT EXISTS renjana_snacks CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE renjana_snacks;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(40) NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NULL DEFAULT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL DEFAULT '',
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('CUSTOMER','ADMIN') NOT NULL DEFAULT 'CUSTOMER',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(48) NOT NULL UNIQUE,
  name VARCHAR(130) NOT NULL,
  variant VARCHAR(80) NOT NULL DEFAULT '',
  category ENUM('Basreng','Makaroni','Usus','Kripca') NOT NULL,
  unit ENUM('PCS','KG') NOT NULL,
  size_label VARCHAR(32) NOT NULL,
  description TEXT NULL,
  price INT UNSIGNED NOT NULL,
  stock DECIMAL(12,3) NOT NULL DEFAULT 0,
  image_filename VARCHAR(150) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (stock >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS store_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  store_name VARCHAR(100) NOT NULL DEFAULT 'CemilIn',
  store_address VARCHAR(500) NOT NULL DEFAULT '',
  headline VARCHAR(180) NOT NULL DEFAULT 'Camilan seru untuk semua suasana.',
  whatsapp VARCHAR(30) NOT NULL DEFAULT '',
  bank_name VARCHAR(40) NOT NULL DEFAULT 'BCA',
  bank_account VARCHAR(40) NOT NULL DEFAULT '',
  bank_holder VARCHAR(100) NOT NULL DEFAULT '',
  qris_filename VARCHAR(150) NULL,
  promo_enabled TINYINT(1) NOT NULL DEFAULT 1,
  min_qty_tier1 INT UNSIGNED NOT NULL DEFAULT 5,
  discount_tier1 INT UNSIGNED NOT NULL DEFAULT 1000, -- diskon TOTAL keranjang, bukan per pcs
  min_qty_tier2 INT UNSIGNED NOT NULL DEFAULT 10,
  discount_tier2 INT UNSIGNED NOT NULL DEFAULT 2000, -- diskon TOTAL keranjang, bukan per pcs
  shipping_flat INT UNSIGNED NOT NULL DEFAULT 0,
  payment_expiry_hours INT UNSIGNED NOT NULL DEFAULT 24,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
INSERT IGNORE INTO store_settings (id) VALUES (1);

CREATE TABLE IF NOT EXISTS cart_items (
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  PRIMARY KEY (user_id, product_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CHECK (quantity > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(32) NOT NULL UNIQUE,
  user_id BIGINT UNSIGNED NOT NULL,
  recipient_name VARCHAR(120) NOT NULL,
  recipient_phone VARCHAR(30) NOT NULL,
  fulfillment ENUM('PICKUP','DELIVERY') NOT NULL,
  address TEXT NULL,
  note VARCHAR(500) NOT NULL DEFAULT '',
  payment_method ENUM('QRIS','BCA') NOT NULL,
  status ENUM('AWAITING_PAYMENT','PAYMENT_REVIEW','PAYMENT_REJECTED','PAID','PROCESSING','READY','SHIPPED','COMPLETED','CANCELLED','EXPIRED') NOT NULL DEFAULT 'AWAITING_PAYMENT',
  subtotal INT UNSIGNED NOT NULL,
  discount INT UNSIGNED NOT NULL DEFAULT 0,
  shipping INT UNSIGNED NOT NULL DEFAULT 0,
  total INT UNSIGNED NOT NULL,
  proof_filename VARCHAR(150) NULL,
  payment_note VARCHAR(500) NULL,
  expires_at DATETIME NOT NULL,
  paid_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_orders_user (user_id,created_at),
  KEY idx_orders_status (status,created_at),
  KEY idx_orders_expiry (status,expires_at),
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(48) NOT NULL,
  name VARCHAR(130) NOT NULL,
  variant VARCHAR(80) NOT NULL,
  unit ENUM('PCS','KG') NOT NULL,
  size_label VARCHAR(32) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit_price INT UNSIGNED NOT NULL,
  unit_discount INT UNSIGNED NOT NULL DEFAULT 0,
  line_total INT UNSIGNED NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB;
